---

version: "3.3"

services:
  nutch:
    image: nutch:msul
    ports:
      - 8082:8080
      - 8081:8081
    command: bash -c "while true; do echo hello; sleep 2; done"
  solr: 
    image: solr:msul
    ports:
      - 80:8983
    command: 
      - /bin/bash
      - -c
      - solr-create -c nutch
